### ISSUE TITLE
heartbeat bug

### ISSUE THREAD

**Issue by zehuamama** [zehuamama/tinybalancer#3]
The proxypass does not write the port, causing the heartbeat detection to kick the url out of the balancer

```yaml
location:                         # route matching for reverse proxy
  - pattern: /
    proxy_pass:                   # URL of the reverse proxy
    - "http://127.0.0.1"
    - "http://127.0.0.1:1013"
    balance_mode: round-robin     # load balancing algorithm
```
